"""PostgreSQL connections. SQLite is only read by the one-time migration."""
import os
from pathlib import Path

import psycopg
from dotenv import load_dotenv
from psycopg.rows import dict_row

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / '.env')


def connect():
    url = os.getenv('DATABASE_URL', '').strip()
    if url and not url.startswith(('postgresql://', 'postgres://')):
        raise ValueError('DATABASE_URL 必须是 PostgreSQL 连接地址')
    # libpq reads PGHOST/PGPORT/PGDATABASE/PGUSER/PGPASSWORD from the environment.
    return psycopg.connect(url, connect_timeout=10, row_factory=dict_row)


def init():
    with connect() as db:
        db.execute('''
        CREATE TABLE IF NOT EXISTS documents(id TEXT PRIMARY KEY, name TEXT NOT NULL, fingerprint TEXT NOT NULL, chunks INTEGER NOT NULL);
        CREATE TABLE IF NOT EXISTS chunks(id TEXT PRIMARY KEY, document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE, location TEXT NOT NULL, text TEXT NOT NULL, tokens TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY, title TEXT NOT NULL, created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
        CREATE TABLE IF NOT EXISTS messages(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, role TEXT NOT NULL, content TEXT NOT NULL, sources TEXT NOT NULL DEFAULT '[]');
        CREATE INDEX IF NOT EXISTS chunks_document_id_idx ON chunks(document_id);
        CREATE INDEX IF NOT EXISTS messages_session_id_id_idx ON messages(session_id,id);
        CREATE TABLE IF NOT EXISTS document_labels(document_id TEXT PRIMARY KEY, company_name TEXT NOT NULL, report_title TEXT NOT NULL, original_filename TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS document_state(document_id TEXT PRIMARY KEY, deleted BOOLEAN NOT NULL DEFAULT FALSE);
        CREATE TABLE IF NOT EXISTS content_edits(block_id TEXT PRIMARY KEY, text TEXT, module TEXT, section TEXT, deleted BOOLEAN NOT NULL DEFAULT FALSE);
        CREATE TABLE IF NOT EXISTS content_audit(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, target_id TEXT, action TEXT, before_value JSONB, created TIMESTAMPTZ DEFAULT now());
        CREATE TABLE IF NOT EXISTS original_profiles(document_id TEXT PRIMARY KEY REFERENCES documents(id) ON DELETE CASCADE, fingerprint TEXT NOT NULL, version INTEGER NOT NULL, profile JSONB NOT NULL);
        CREATE TABLE IF NOT EXISTS document_versions(new_document_id TEXT PRIMARY KEY REFERENCES documents(id), previous_document_id TEXT NOT NULL REFERENCES documents(id), created TIMESTAMPTZ NOT NULL DEFAULT now());
        CREATE TABLE IF NOT EXISTS dedup_models(id TEXT PRIMARY KEY, active BOOLEAN NOT NULL DEFAULT FALSE, weights JSONB NOT NULL, unseen DOUBLE PRECISION NOT NULL, created TIMESTAMPTZ NOT NULL DEFAULT now());
        CREATE UNIQUE INDEX IF NOT EXISTS dedup_active_model ON dedup_models(active) WHERE active;
        CREATE TABLE IF NOT EXISTS dedup_documents(document_id TEXT PRIMARY KEY REFERENCES documents(id) ON DELETE CASCADE, fingerprint TEXT NOT NULL, profile_version INTEGER NOT NULL, index_version TEXT NOT NULL, model_id TEXT NOT NULL REFERENCES dedup_models(id), exact_hash TEXT NOT NULL, shingles JSONB NOT NULL, weight_total DOUBLE PRECISION NOT NULL);
        CREATE INDEX IF NOT EXISTS dedup_exact ON dedup_documents(exact_hash);
        CREATE INDEX IF NOT EXISTS documents_fingerprint ON documents(fingerprint);
        CREATE TABLE IF NOT EXISTS dedup_buckets(document_id TEXT NOT NULL REFERENCES dedup_documents(document_id) ON DELETE CASCADE, model_id TEXT NOT NULL, scope TEXT NOT NULL, band INTEGER NOT NULL, bucket BIGINT NOT NULL, PRIMARY KEY(document_id,scope,band));
        CREATE INDEX IF NOT EXISTS dedup_bucket_lookup ON dedup_buckets(model_id,scope,band,bucket);
        ''')
